# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 paths:
   include:
     - 'src/code/input/*'
 branches:
   include:
    - main

#variables:
#    - template: variables.yml
  
pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Setup
  jobs:
    - job: Setup
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.13.2'

      - script: |
              ls $(System.DefaultWorkingDirectory)
              echo "terraform build started.."
              cd $(System.DefaultWorkingDirectory)/platform
              echo "list all the files"
              ls 
        displayName: 'Setup Enviroment'
      
- stage: Plan_Dev
  dependsOn: [Setup]
  jobs:
    - job: Plan_Dev
      steps:
      - script: |
              ls $(System.DefaultWorkingDirectory)
              echo "=====================List all the files of main folder============================"
              cd $(System.DefaultWorkingDirectory)/platform
              
              #echo "========================================== COPY File to dev environment ======================================"
              
              #cp -v -r * $(System.DefaultWorkingDirectory)/src/dev 
              #cd $(System.DefaultWorkingDirectory)/src/dev
              echo "list all the files"
              ls 
              ls ../env/dev
              #az login --service-principal -u 290f6b48-7a20-4473-aea2-087b240ac884 -p BVL8Q~qPOsHHnaFLnLyHIw65mfQ5TT6UYO6sHbwB --tenant 6594e148-8146-4b66-b2ea-704e1a0d83c0
              export ARM_CLIENT_ID="290f6b48-7a20-4473-aea2-087b240ac884"
              export ARM_CLIENT_SECRET="BVL8Q~qPOsHHnaFLnLyHIw65mfQ5TT6UYO6sHbwB"
              export ARM_SUBSCRIPTION_ID="78b403c6-7d6d-4d7f-b32c-5635479016fb"
              export ARM_TENANT_ID="6594e148-8146-4b66-b2ea-704e1a0d83c0"
              terraform init
               
               echo ##############~~~~~~~~~~~~~~~Terraform Plan~~~~~~~~~~~~~~###############
              terraform plan -var-file="../env/dev/dev-env.tfvars" -out="out.plan"
        displayName: 'build stage'
    
      - task: CopyFiles@2
        inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/platform'
            Contents: |
                      **
                      !dev/.terraform/**/*
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy Artifacts'

      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: dev_artifacts

- stage: Apply_On_Dev
  dependsOn: [Setup, Plan_Dev]
  jobs:
  - deployment: 
    displayName: DEV
    environment: DEV
    strategy:
     runOnce:
        deploy:
           steps:
            - download: current 
              artifact: dev_artifacts
            - script: |
                    echo "Deploy to Move to directory"
                      ls $(Pipeline.Workspace)/dev_artifacts/
                      echo "=====================List all the files of main folder============================"
                      cd $(Pipeline.Workspace)/dev_artifacts/
                      
                      #echo "========================================== COPY File to dev environment ======================================"
                      
                      #cp -v -r * $(Pipeline.Workspace)/src/dev 
                     az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
                     terraform init -backend-config="storage_account_name=$(tfBackendStorageAccountName)" -backend-config="container_name=$(tfBackendStorageContainerName)" -backend-config="access_key=$(tfBackendSAAccessKey)" -backend-config="key=$(tfBackendFileName)-dev"
               
                     echo ##############~~~~~~~~~~~~~~~Terraform Plan~~~~~~~~~~~~~~###############
                     terraform plan -var-file=./input/dev.tfvars.json -out="out.plan" -var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)" 
        
                    echo '#######Terraform Apply########'

                    terraform apply out.plan
              displayName: Apply
